// Generated by CSS Grid Editor
import styled from "styled-components";

export default styled.div`
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-columns: 10vw 280px 10px 420px 10px 420px 10px 420px 10px 280px 10px 280px 10px 280px 10px 420px 10vw;
  grid-template-rows: 140px 10px 140px 10px 140px 10px 140px;
  grid-template-areas:
    "p1 g1 g1 g1 . g5 . g7 . g10 . g11 .   g12 . g15 p2"
    "p1 g1 g1 g1 . .  . .  . g10 . g11 .   g12 . g15 p2"
    "p1 g1 g1 g1 . g6 . g8 . g10 . g11 .   g12 . g15 p2"
    "p1 .  .  .  . g6 . .  . g10 . .   .   .   . .   p2"
    "p1 g2 .  g4 . g6 . g9 . g10 . g13 g13 g13 . g16 p2"
    "p1 .  .  g4 . g6 . g9 . g10 . .   .   .   . g16 p2"
    "p1 g3 .  g4 . g6 . g9 . g10 . g14 g14 g14 . g16 p2";
  overflow: overlay;
`;

type AreaProps = {
  gridArea: string;
};
export const Area = styled.div`
  grid-area: ${(props: AreaProps) => props.gridArea};
  background-color: #ccc;
`;

type PaddingProps = {
  gridArea: string;
};
export const Padding = styled.div`
  grid-area: ${(props: PaddingProps) => props.gridArea};
`;
